version: "3"

services:
  wirtbot:
    build: ..
    ports: [3030:3030]
    restart: always
    volumes: ["..:/app"]
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "info"
    container_name: development_wirtbot
    command: ["cargo", "watch", "-x", "run"]
