version: "3"

services:
  test_wirtbot:
    build: 
      context: ../../..
      dockerfile: WirtBot/docker/DevDockerfile
    ports: [3030:3030]
    restart: always
    volumes: ["../..:/app"]
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "debug"
      "MANAGED_DNS_ENABLED": 1
    container_name: test_wirtbot
    command: ["cargo", "test"]
