- name: Install vim
  apt:
    name:
      - vim
      - docker.io
      - docker-compose
    state: present


- name: Copy docker-daemon config to machine
  template:
    src: "templates/docker-daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: 0640

- name: Start and enable docker
  systemd:
    state: started
    enabled: yes
    name: docker

- name: Restart docker to load daemon config
  systemd:
    state: restarted
    name: docker