- name: set a strict default sshd configuration
  template:
    src: templates/sshd.config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0640

- name: restart sshd service
  service:
    name: sshd
    state: restarted
