
- name: Create directories for wirtbot
  file:
    path: "/home/{{ maintainer_username }}/{{ item }}"
    owner: "{{ maintainer_username }}"
    group: "{{ maintainer_username }}"
    state: directory
    mode: '0750'
  loop:
   - WirtBot 
   - WirtBot/data

- name: Copy docker-compose file to machine
  template:
    src: "templates/WirtBot.docker-compose.yml.j2"
    dest: "/home/{{ maintainer_username }}/WirtBot/docker-compose.yml"
    owner: "{{ maintainer_username }}"
    group: "{{ maintainer_username }}"
    mode: 0640

- name: Copy coredns config to machine
  template:
    src: "templates/coredns.config.j2"
    dest: "/home/{{ maintainer_username }}/WirtBot/data/Corefile"
    owner: "{{ maintainer_username }}"
    group: "{{ maintainer_username }}"
    mode: 0640
    force: no

- name: Start WirtBot docker service
  docker_compose:
    project_src: "/home/{{ maintainer_username }}/WirtBot"
    build: yes
    recreate: always
    pull: yes