version: "3"

services:
  wirtbot_unit_tests:
    build: 
      context: ../..
      dockerfile: build-automation/Unit-Tests/Dockerfile
    restart: always
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "debug"
      "MANAGED_DNS_ENABLED": 1
    container_name: wirtbot_unit_tests
