name: run Unit tests

on:
  pull_request:
    branches: [master]
    paths:
      - "Core/**"
      - "shared-libs/**"
      - "Interface/**"
      - "Installer/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Trigger tests
        run: |
          make test-unit-ci
