name: run WirtBot shared-lib tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]
    paths:
      - "shared-libs/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run test suite for the whole System
        run: |
            cd shared-libs/config-generators && npm ci && npm run test && cd - && \
            cd shared-libs/rust-wasm && npm ci && npm run test && cd -



